### ISSUE TITLE
Support for full WebSocket Request/Response type message handling

### ISSUE THREAD

**Issue by rahulakash** [stevenroose/dart-websockets#6]
Hello,

Thank you for this library! It would be a great to have a standard WebSocket Request/Response type implementation similar to the HTTP request/response implementation.

Is there a easy way to achieve this with the current  dart-websockets library? Any ideas and suggestions are highly appreciated.

**Comment by stevenroose** [comment]
Can you be more specific in what exactly you are looking for?

**Comment by rahulakash** [comment]
@stevenroose : I am looking for a functionality similar to HTTP Request and Response model. I am aware that using WebSockets, we do not have this mechanism built-in since there is not really a response which has to follow on a request, we just exchange data with no relation to each other. I was wondering if there is a way to achieve this.

Background: I have developed a web application with client-server communication happening via WebSocket. I am in a situation where I send a message to the server with `socket.add('some_data')` and listen for messages back from server with `socket.listen(onMessage)`. But there is no way to associate a response message to the request. I hope this makes my question a little clear. Please let me know if you need more explanation :)

**Comment by stevenroose** [comment]
I advise you to take a look at the JSON-RPC v2 documentation. It's a
standard for doing RPC over WebSockets and has things like
response-to-request matching built-in.

Since that is something both server and client should be aware of, it is
best implemented by making use of a standard. Otherwise you could always
implement it yourself by having your client add an extra field like `id` or
`sequence` that the server should copy in the responses.

**Comment by rahulakash** [comment]
@stevenroose Thank you for your suggestion. I was thinking along the same line, adding a 'sequence' or 'id' in the client request would be a quick way to move forward. I will also look into JSON-RPC. I appreciate you swift response! Cheers :)
